apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-service
  namespace: todo-app-dev
  labels:
    app: todo-frontend
spec:
  type: NodePort
  selector:
    app: todo-frontend
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
