apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-service
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    {{- include "todo-app.frontend.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "todo-app.frontend.selectorLabels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
    {{- if .Values.frontend.service.nodePort }}
    nodePort: {{ .Values.frontend.service.nodePort }}
    {{- end }}
