apiVersion: v1
kind: Secret
metadata:
  name: todo-app-secrets
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.backend.env.DATABASE_URL | quote }}
  JWT_SECRET: {{ .Values.backend.env.JWT_SECRET | quote }}
  GEMINI_API_KEY: {{ .Values.backend.env.GEMINI_API_KEY | quote }}
  BETTER_AUTH_SECRET: {{ .Values.backend.env.BETTER_AUTH_SECRET | quote }}
